version: '3'
services:
  mysql-server-1:
    container_name: mysql-server-1
    env_file:
      - ./mysql/mysql-server.env
    image: mysql/mysql-server:8.0.12
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON",
              "--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql",
              "--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
  mysql-server-2:
    container_name: mysql-server-2
    env_file:
      - ./mysql/mysql-server.env
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON",
              "--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql",
              "--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
  mysql-server-3:
    container_name: mysql-server-3
    env_file:
      - ./mysql/mysql-server.env
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON",
              "--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql",
              "--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
  
  mysql-shell:
    container_name: mysql-shell
    env_file:
      - ./mysql/mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./mysql/scripts/:/scripts/
    depends_on:
      mysql-server-1:
        condition: service_healthy
      mysql-server-2:
        condition: service_healthy
      mysql-server-3:
        condition: service_healthy
  
  mysql-router:
    container_name: mysql-router
    env_file:
      - ./mysql/mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql-router
      PMA_PORT: 6446
      PMA_USER: dbwebapp
      PMA_PASSWORD: dbwebapp
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql-router
    restart: unless-stopped