services:
  mysql-server-1:
    container_name: mysql-server-1
    env_file:
      - ./mysql/mysql-server.env
    image: mysql:8.4.7
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--gtid_mode=ON","--enforce_gtid_consistency=ON"]
    volumes:
      - mysql-data-1:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      timeout: 10s
      retries: 20
      interval: 5s
      start_period: 30s

  mysql-server-2:
    container_name: mysql-server-2
    env_file:
      - ./mysql/mysql-server.env
    image: mysql:8.4.7
    command: ["mysqld","--server_id=2","--gtid_mode=ON","--enforce_gtid_consistency=ON"]
    ports:
      - "3302:3306"
    volumes:
      - mysql-data-2:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      timeout: 10s
      retries: 20
      interval: 5s
      start_period: 30s

  mysql-server-3:
    container_name: mysql-server-3
    env_file:
      - ./mysql/mysql-server.env
    image: mysql:8.4.7
    command: ["mysqld","--server_id=3","--gtid_mode=ON","--enforce_gtid_consistency=ON"]
    ports:
      - "3303:3306"
    volumes:
      - mysql-data-3:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysql"]
      timeout: 10s
      retries: 20
      interval: 5s
      start_period: 30s

  mysql-shell:
    container_name: mysql-shell
    image: mysql:8.4.7
    volumes:
      - ./mysql/shell:/scripts
    command:
      ["mysqlsh","-h","mysql-server-1","-uroot","-pmysql","--file","/scripts/SetupCluster.js"]
    depends_on:
      mysql-server-1:
        condition: service_healthy
      mysql-server-2:
        condition: service_healthy
      mysql-server-3:
        condition: service_healthy


  mysql-router:
    image: container-registry.oracle.com/mysql/community-router:8.4.7
    container_name: mysql-router
    ports:
      - "6446:6446"   # Read/Write port
      - "6447:6447"   # Read-Only port
      - "6448:6448"   # Classic MySQL protocol port
      - "8443:8443"   # HTTP port for REST API
    env_file:
      - ./mysql/mysql-router.env
    depends_on:
      mysql-server-1:
        condition: service_healthy
      mysql-server-2:
        condition: service_healthy
      mysql-server-3:
        condition: service_healthy
    restart: on-failure

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql-router
      PMA_PORT: 6446
      PMA_USER: root
      PMA_PASSWORD: mysql
    depends_on:
      - mysql-router
        
    restart: unless-stopped

# Define volumes for persistence
volumes:
  mysql-data-1:
  mysql-data-2:
  mysql-data-3: